### ISSUE TITLE
Can I use this tool in plant?

### ISSUE THREAD

**Issue by hanshanmengqi** [fzbio/GILoop#2]
Hi Fuzhou,

Thanks for developing such a powerful tool.

I'm working on plant, so I'm curious whether I can use this tool in plant HiC data.

Thanks!
Han

**Comment by wangfuzhou110** [comment]
Hi Han,

Thank you for reaching out! Unfortunately, for now the tool only supports loop detection in mammalian Hi-C. To the best of my knowledge, plant does not have CTCF, and therefore this tool cannot be applied because it was designed to detect CTCF-mediated loops. 

Cheers,
Fuzhou
